# Generated by Django 3.0.14 on 2022-08-10 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=15)),
                ('party_name', models.CharField(max_length=200)),
                ('party_size', models.IntegerField(default=0)),
                ('party_date', models.DateField(blank=True, null=True)),
                ('party_start_time', models.TimeField(blank=True, null=True)),
                ('party_end_time', models.TimeField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
