# Generated by Django 3.0.14 on 2022-08-10 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ServiceReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='events.Reservation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Service')),
            ],
        ),
        migrations.CreateModel(
            name='PerformerReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Performer')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performers', to='events.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='MascotReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mascot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Mascot')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascots', to='events.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Equipment')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='events.Reservation')),
            ],
        ),
    ]
