# Generated by Django 3.0.14 on 2022-08-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20220811_0030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentreservation',
            unique_together={('equipment', 'reservation')},
        ),
        migrations.AlterUniqueTogether(
            name='mascotreservation',
            unique_together={('mascot', 'reservation')},
        ),
        migrations.AlterUniqueTogether(
            name='performerreservation',
            unique_together={('performer', 'reservation')},
        ),
        migrations.AlterUniqueTogether(
            name='servicereservation',
            unique_together={('service', 'reservation')},
        ),
    ]
