# Generated by Django 3.0.14 on 2022-08-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20220811_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='party_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='party_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='party_start_time',
            field=models.TimeField(),
        ),
    ]
