# Generated by Django 3.0.14 on 2022-08-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_product_productpurchase_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ballo', 'Balloons'), ('banne', 'Banners'), ('gRBox', 'Gender Reveal Box'), ('gWrap', 'Gift Wrapper'), ('tACha', 'Table and Chairs'), ('dCurt', 'Decorative Curtains'), ('cTopp', 'Cake Toppers')], default='tACha', max_length=5),
            preserve_default=False,
        ),
    ]
