# Generated by Django 3.0.14 on 2022-08-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='TO PAY', max_length=15),
        ),
    ]
