# Generated by Django 3.0.14 on 2022-08-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('COD', 'COD')], default='COD', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('TO PAY', 'TO PAY'), ('PREPARING', 'PREPARING'), ('SHIPPED OUT', 'SHIPPED OUT'), ('DELIVERED', 'DELIVERED')], default='TO PAY', max_length=15),
        ),
    ]
