# Generated by Django 3.0.14 on 2022-08-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_purchase_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
