# Generated by Django 3.0.14 on 2022-08-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20220818_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
