# Generated by Django 3.0.14 on 2022-08-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_performerapplication_hash_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='performerapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=15),
        ),
    ]
