# Generated by Django 3.0.14 on 2022-08-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_performerapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='performerapplication',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
