# Generated by Django 3.0.14 on 2022-08-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active_purchase_id',
            field=models.IntegerField(default=0),
        ),
    ]
