# Generated by Django 3.0.14 on 2022-08-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_active_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cart_size',
            field=models.IntegerField(default=0),
        ),
    ]
