# Generated by Django 3.0.14 on 2022-08-18 07:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220818_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 18, 7, 26, 11, 743681, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
